### ISSUE TITLE
La synchro ne fonctionne pas quand les contacts sont ajoutés en lot au groupe

### ISSUE THREAD

**Issue by dev-allinappli** [wyde22/groupsyncwithrole#10]
J'ai fait une recherche sur un champ CiviCRM et avec le résultat, j'ai ajouté les contacts à un groupe. Ils sont bien ajoutés mais les comptes ne sont pas synchronisés. Pour ceux qui n'avaient pas de comptes WP ce n'est pas grave mais il y en avait plein qui avaient un compte utilisateur WP et le rôle issu de la synchronisation n'a pas été ajouté.

J'ai effacé et reparamétré la synchro et c'est sans effet aussi. J'ai vidé les caches et fait tourner les cronjobs mais pareil.

côté WP pour les comptes
![image](https://github.com/user-attachments/assets/b274e6f3-0dc5-4a26-bb7a-c887e4009d30)

côté CiviCRM pour les groupes
![image](https://github.com/user-attachments/assets/b8c5322a-f9ac-4ab0-bb00-ffe6795790fc)

**Comment by dev-allinappli** [comment]
en fait ça fonctionne quand l'ajout est manuel > j'ai supprimé le contact du groupe pour effacer l'historique et je l'ai ajouté à nouveau au groupe > la synchro se fait bien

**Comment by wyde22** [comment]
@allinappliadmin j'ai fait une branche spécifique pour ce travail **bulk-group-contact**. Je prends en charge le traitement en lot de l'ajout de contacts dans un groupe synchronisé avec un rôle WP.

je ne prends pas en compte la création d'un utilisateur WP quand un contact civicrm existe dans le crm et que celui ci ne possède pas d'utilisateur WP lors du traitement en lot. Je fais cela uniquement pour un contact. Tu peux faire un pull du repo si tu veux

**Comment by dev-allinappli** [comment]
bravo ! ready to merge :-)
