### ISSUE TITLE
Lors d'un ajout d'un contact dans un groupe CiviCRM, vérifier la présence de ce contact en tant que user WordPress

### ISSUE THREAD

**Issue by wyde22** [wyde22/groupsyncwithrole#2]
A ce jour l'extension permet de mapper un groupe CiviCRM avec un rôle WordPress. Le contact doit être présent dans la table `UFMatch` du crm

idéalement il peut être intéressant d'avoir le process suivant : 
- ajout d'un contact dans un groupe CiviCRM depuis le back office crm
- vérification de ce contact dans WordPress afin de vérifier si ce contact est enregistré dans le cms
- si le contact n'est pas présent : création de l'user dans WordPress et ajout du rôle
- si le contact est présent synchronisation du rôle de l'user WordPress avec le groupe CiviCRM

**Comment by dev-allinappli** [comment]
- en cas de retrait/suppression du contact du groupe, retirer le rôle WP à l'utilisateur. Prévoir dans l'interface de gestion ce cas pour décider quel est le rôle par défaut (fallback) : anonyme, subscriber ou tout autre rôle. Cela permet de gérer finement les droits accordés à un contact : par exemple s'il était dans le groupe 'admin' avec le rôle 'admin' et qu'il est retiré du groupe 'admin' alors il perd ce rôle.

**Comment by wyde22** [comment]
@allinappliadmin je crois que nativement civicrm le permet. Un utilisateur est créé avec le rôle par défaut abonné. Si l'utilisateur avec ce rôle par défaut se trouve dans un groupe 'admin' il aura le rôle 'admin'. Si il quitte ce groupe il aura le rôle abonné par défaut soit abonné

on laisse un rôle par défaut à abonné ?

pour info j'ai fait le nécessaire pour créer un user WP si celui ci n'est pas présent. L'envoi d'emai ne fonctionne pas bien chez moi ma plateforme n'est pas paramétré pour envoyer des emails.

est ce que tu as une plateforme de dev pour continuer mes tests avec mon extension ?

**Comment by dev-allinappli** [comment]
> je crois que nativement civicrm le permet. Un utilisateur est créé avec le rôle par défaut abonné. Si l'utilisateur avec ce rôle par défaut se trouve dans un groupe 'admin' il aura le rôle 'admin'. Si il quitte ce groupe il aura le rôle abonné par défaut soit abonné
> on laisse un rôle par défaut à abonné ?

si c'est possible je pense que c'est mieux d'avoir un option de paramétrage pour offrir la possibilité de décider si la personne qui avait le rôle X est rétrogradée en W, Y ou Z

**Comment by dev-allinappli** [comment]
> pour info j'ai fait le nécessaire pour créer un user WP si celui ci n'est pas présent. L'envoi d'emai ne fonctionne pas bien chez moi ma plateforme n'est pas paramétré pour envoyer des emails.

super

**Comment by wyde22** [comment]
la création d'un user WP si celui ci n'existe pas dans l'instance fonctionne correctement par contre l'envoi d'email ne fonctionne pas. J'ai l'erreur suivante : 
```
Register new user error : WP_Error Object
(
    [errors] => Array
        (
            [username_exists] => Array
                (
                    [0] => <strong>Erreur :</strong> cet identifiant est déjà utilisé. Veuillez en choisir un autre.
                )

            [email_exists] => Array
                (
                    [0] => <strong>Erreur :</strong> cette adresse e-mail est déjà inscrite. <a href="https://dewy2-dev.inoede.symbiodev.xyz/wp-login.php">Connectez-vous</a> avec cette adresse ou choisissez-en une autre.
                )

        )

    [error_data] => Array
        (
        )

    [additional_data:protected] => Array
        (
        )

)
```

c'est bizarre car l'username n'est pas présent dans la base WP et ni le mail. J'ai du mal à comprendre pourquoi j'ai cette erreur

**Comment by wyde22** [comment]
j'ai fait autrement en utilisant une méthode native du core de CiviCRM avec succès. Voir le ticket suivant : #5

**Comment by wyde22** [comment]
solution trouvée
