### ISSUE TITLE
La fonction register new user n'envoi pas d'email suite à la création d'un nouveau user

### ISSUE THREAD

**Issue by wyde22** [wyde22/groupsyncwithrole#5]
l'envoi d'email ne fonctionne pas suite à l'inscription d'un user WP. J'ai l'erreur suivante : 
```
Register new user error : WP_Error Object
(
    [errors] => Array
        (
            [username_exists] => Array
                (
                    [0] => <strong>Erreur :</strong> cet identifiant est déjà utilisé. Veuillez en choisir un autre.
                )

            [email_exists] => Array
                (
                    [0] => <strong>Erreur :</strong> cette adresse e-mail est déjà inscrite. <a href="https://dewy2-dev.inoede.symbiodev.xyz/wp-login.php">Connectez-vous</a> avec cette adresse ou choisissez-en une autre.
                )

        )

    [error_data] => Array
        (
        )

    [additional_data:protected] => Array
        (
        )

)
```

c'est bizarre car la donnée n'est pas présente dans la base WP. on dirait un problème de priorité dans les hooks

**Comment by wyde22** [comment]
J'ai trouvé une solution en espérant que celle ci soit la meilleure. En fait il existe dans le core de CiviCRM une méthode qui associe le contact à un utilisateur WordPress : `CRM_Core_BAO_CMSUser::create($cmsUserParams, 'email');`. Cette méthode créée le contact dans la table `UFMatch` et ensuite le mail de notification d'un nouvel utilisateur est correctement envoyé également. A ta disposition pour échanger si besoin

**Comment by dev-allinappli** [comment]
> J'ai trouvé une solution en espérant que celle ci soit la meilleure. En fait il existe dans le core de CiviCRM une méthode qui associe le contact à un utilisateur WordPress : CRM_Core_BAO_CMSUser::create($cmsUserParams, 'email');. Cette méthode créée le contact dans la table UFMatch et ensuite le mail de notification d'un nouvel utilisateur est correctement envoyé également. A ta disposition pour échanger si besoin

j'imagine que la méthode ajout l'utilisateur dans la table 'user' du CMS ainsi que UFMatch qui n'est suffisante non ?

**Comment by wyde22** [comment]
oui les tables `wp_users `et `UFMatch `sont correctement implémentées

**Comment by wyde22** [comment]
problème résolu
