### ISSUE TITLE
Par défaut CiviCRM créé l'utilisateur avec le rôle par défaut paramétré sur WordPress. Donner la possibilité de modifier ce paramétrage à l'utilisateur

### ISSUE THREAD

**Issue by wyde22** [wyde22/groupsyncwithrole#6]
nativement CiviCRM créé l'utilisateur WordPress avec le rôle par défaut paramétré dans le paramétrage de WordPress : 

![Réglages-généraux-‹-dewy2-dev-inoede-symbiodev-xyz-—-WordPress-09-25-2024_11_32_AM](https://github.com/user-attachments/assets/4b0be3db-ffa6-4833-a2c7-aec41da6d08a)

l'idée est de trouver un moyen à l'utilisateur de désactiver cette fonctionnalité native du CRM

**Comment by wyde22** [comment]
@allinappliadmin j'ai trouvé une solution pour cette problématique. J'ai jouté un champ radio dans le panneau de setting de l'extension afin que l'utilisateur puisse activer ou non l'ajout du rôle par défaut WP lors de la synchronisation.

![Settings-for-Sync-group-CiviCRM-to-WordPress-role-‹-dewy2-dev-inoede-symbiodev-xyz-—-WordPress-09-25-2024_11_34_AM](https://github.com/user-attachments/assets/ba2c7818-8639-41d3-a739-b82a325a4927)

ensuite dans le `hook_civicrm_post` j'utilise une fonction qui contrôle le paramétrage de ce setting et selon le paramétrage je fais une suppression du rôle par défaut lors de la synchronisation. Je fais cette opération dans le cas ou on ajoute un contact dans un groupe CiviCRM et que celui ci ne possède pas de rôle WordPress. 

la logique d'activation / désactivation du rôle par défaut se trouve dans une fonction que je peux ajouter ou tu veux si besoin. A échanger ensemble si besoin.

le code se trouve sur la branche [travail-default-role](https://github.com/wyde22/groupsyncwithrole/tree/travail-default-role)

**Comment by dev-allinappli** [comment]
ok ça paraît aller dans la bonne direction, je dois tester

**Comment by dev-allinappli** [comment]
l'option marche nickel, le contact a bien été créé avec uniquement un rôle

**Comment by dev-allinappli** [comment]
dans le sens contraire, je ne sais plus si on l'avait géré mais le contact n'a plus de rôle

![image](https://github.com/user-attachments/assets/a47ae356-d419-490c-800b-15707da38b53)

comment traite-t-on ce cas ? est-ce qu'on considère que c'est 'aucun', 'rôle wp par défaut' ou on donne le choix dans la page de settings pour déclarer le fallback ? Christian Wach le propose dans membersync, on peut choisir le rôle que la personne obtient quand elle est retirée du groupe

**Comment by Guydn** [comment]
Mon point de vue sur la question est que je laisserai la création par défaut sur Abonné (rôle standard de WP, qui n'a aucun accès et que je ne change jamais). Quad on enlève les rôles, je sais que le compte aura toujours ce rôle, et je pense que (mais je ne suis pas sur) que c'est mieux (pour le système) qu'un compte ait au moins un rôle...

**Comment by wyde22** [comment]
> dans le sens contraire, je ne sais plus si on l'avait géré mais le contact n'a plus de rôle

effectivement lors de mes tests j'ai vu cette problématique. Je viens de refaire un test en ajoutant un contact sans user WP dans un groupe civicrm. Préalablement j'ai désactivé l'option par défaut de création de l'user WP avec le rôle par défaut. L'user WP est correctement créé sans le rôle par défaut.

Ensuite j'ai retirer le contact du groupe et l'user WP n'a aucun rôle. Via l'extension user switching j'ai fait un test de connexion afin de vérifier le comportement du site sur cet user avec aucun rôle.

il y a aucun bug sur cette connexion et le site fonctionne correctement. 
![Vous-n’avez-pas-l’autorisation-d’accéder-à-cette-page-–-dewy2-dev-inoede-symbiodev-xyz-10-01-2024_09_57_AM](https://github.com/user-attachments/assets/17e1d665-7512-450f-90dc-0c60d186d386)

le fonctionnement du site sur cet utilisateur sans rôle se rapproche d'un user avec le rôle abonné.

donc pour moi, mon code est peut être superflu.

**Comment by wyde22** [comment]
suite à notre discussion avec @allinappliadmin j'ai fait une modification dans le code. En effet, en ajoutant le paramétrage pour enlever l'ajout du rôle par défaut à la création d'un user role, on avait un souci car un utilisateur pouvait se trouver sans aucun rôle.

or cela peut être problématique car un user avec un compte WP sans aucun rôle pouvait visualiser un profil par exemple. du coup, l'administrateur du crm n'a pas la main sur ce type de compte sans rôle. Dans mon code j'ai fait en sorte d'ajouter un rôle `anonymous_user` quand l'utilisateur n'est plus dans un groupe

de plus il fallait également ajouter un cas. si ce même utilisateur avec le rôle `anonymous_user` est réintégré dans un groupe il faut gérer ce cas et enlever le rôle `anonymous_user`. j'ai fait le nécessaire
