### ISSUE TITLE
le bouton Remove Sync apparait de façon parasite dans paramètres Civievent

### ISSUE THREAD

**Issue by Guydn** [wyde22/groupsyncwithrole#8]
Un truc bizarre 
![Civi group sync bug](https://github.com/user-attachments/assets/46f5a3fb-1bc5-4e56-9479-525da4a2c757)

Testé surtestwpcivi

**Comment by wyde22** [comment]
ok j'ai vu le problème. J'avais un fichier js chargé en global sur les pages CiviCRM. J'ai fait le nécessaire afin que ce script js soit chargé uniquement sur la page admin de cette extension. Je vais pusher mes modifications. Je reviens vers toi dès que cela est réalisé

**Comment by wyde22** [comment]
@Guydn @allinappliadmin la correction est poussée sur master
